const CONSTANTS = {
    DEFAULT: "DEFAULT",
    INDEX: "INDEX",
    QUERY_ANALYSIS: "QUERY_ANALYSIS",
    CONNECTION_ANALYSIS: "CONNECTION_ANALYSIS",
    WORK_LOAD_ANALYSIS: "WORK_LOAD_ANALYSIS",
    CLUSTER_EVENT_ANALYSIS: "CLUSTER_EVENT_ANALYSIS" 
}

export default CONSTANTS;