const DisplayNameMappers = {
  nCOLLSCAN: "Total Collection Scans",
  nSlowOps: "Total Slow Ops",
  nFind: "Total Find Ops",
  nGetMore: "Total GetMore Ops",
  nAggregate: "Total Aggregate Ops",
  nInsert: "Total Insert Ops",
  nUpdate: "Total Update Ops",
  nCount: "Total Count Ops",
  slowestOp: "Slowest Op",
  redundantIdx: "Redundant Indexes",
  unusedIdx: "Unused Indexes",
  totalIdx: "Total Indexes",
  totalCollections: "Total Collections",
  active_connections: "Active Connections",
  available_connections: "Available Connections",
  current_connections: "Current Connections",
  total_created_connections: "Total Created Connections",
  "i": "Insert",
  "u": "Update",
  "d": "Delete",
  "c": "db Command",
  "n": "No Op",
  configuredSize: "Oplog Size (MB)",
  timeDiffHours: "Replication Window (Hours)",
  oplogGbPerHour: "Oplog GB/HR",
  recomendedAtlas: "Minimum Recomended Oplog Size (MB)"
}

export default DisplayNameMappers;